Traceback (most recent call last):
  File "/mnt/python/miniforge3/envs/sphinx/lib/python3.13/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
    ~~~~~~~~~^
        nb,
        ^^^
    ...<4 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/mnt/python/miniforge3/envs/sphinx/lib/python3.13/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/mnt/python/miniforge3/envs/sphinx/lib/python3.13/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/mnt/python/miniforge3/envs/sphinx/lib/python3.13/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/mnt/python/miniforge3/envs/sphinx/lib/python3.13/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
        cell, index, execution_count=self.code_cells_executed + 1
    )
  File "/mnt/python/miniforge3/envs/sphinx/lib/python3.13/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/mnt/python/miniforge3/envs/sphinx/lib/python3.13/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
M = np.matrix([0.05, 0.36, 0.50, 0.09,
              0.01, 0.57, 0.25, 0.17,
              0.0,0.14,0.55,0.31,
              0.0,0.01,0.03,0.96]).reshape(4,4).T
M
------------------


[31m---------------------------------------------------------------------------[39m
[31mModuleNotFoundError[39m                       Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[1][39m[32m, line 1[39m
[32m----> [39m[32m1[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mnumpy[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mnp[39;00m
[32m      2[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mmatplotlib[39;00m[34;01m.[39;00m[34;01mpyplot[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mplt[39;00m
[32m      3[39m M = np.matrix([[32m0.05[39m, [32m0.36[39m, [32m0.50[39m, [32m0.09[39m,
[32m      4[39m               [32m0.01[39m, [32m0.57[39m, [32m0.25[39m, [32m0.17[39m,
[32m      5[39m               [32m0.0[39m,[32m0.14[39m,[32m0.55[39m,[32m0.31[39m,
[32m      6[39m               [32m0.0[39m,[32m0.01[39m,[32m0.03[39m,[32m0.96[39m]).reshape([32m4[39m,[32m4[39m).T

[31mModuleNotFoundError[39m: No module named 'numpy'

